service: serverless-banking-login-amplify-hosted

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  fetchUserData:
    handler: handler.fetchUserData
    events:
      - http:
          path: user/data
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-east-2:992382508838:userpool/us-east-2_XVEe527sL
